spring:
  application:
    name: grpc-server
  sleuth:
    enabled: true
    sampler:
      probability: 1.0F

  zipkin:
    base-url: http://tracing.accounts-internal-stg-cloud.paytm.com

grpc:
  server:
    port: 18888

sample:
  zipkin:
    enabled: true